### PR TITLE
Readme-Main

### PR DESCRIPTION
**Pull request by Desalubrious**
Add readme to main branch

### CODE REVIEW

**Review by kwing25 — APPROVED** [review]
good

**Review by CobaltFrostfish — APPROVED** [review]
Looks good!

**Review by Jared-N2 — COMMENTED** [review]
good

**Review by Jared-N2 — APPROVED** [review]

**Comment by kwing25** [comment]
all good

**Comment by Desalubrious** [comment]
pls

**Review by Jared-N2 — APPROVED** [review]

**Pull request merged**
